hc10dt_arm_controller:
  type: velocity_controllers/JointTrajectoryController
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10
  joints:
     - joint_1_s
     - joint_2_l
     - joint_3_u
     - joint_4_r
     - joint_5_b
     - joint_6_t
  constraints:
      joint_1_s: {trajectory: 0.1, goal: 0.1}
      joint_2_l: {trajectory: 0.1, goal: 0.1}
      joint_3_u: {trajectory: 0.1, goal: 0.1}
      joint_4_r: {trajectory: 0.1, goal: 0.1}
      joint_5_b: {trajectory: 0.1, goal: 0.1}
      joint_6_t: {trajectory: 0.1, goal: 0.1}

  gains: # Required because we're controlling a velocity interface
    joint_1_s: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_2_l: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_3_u: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_4_r: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_5_b: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_6_t: {p: 100,  d: 1, i: 1, i_clamp: 1}
